#!/usr/bin/env python3
"""Render docs/*.md performance/accuracy pages from real artifacts —
never hand-typed numbers (CLAUDE.md §3.2; PLAN.md A12 item 1: "docs/ 下
所有性能与准确率数字由脚本从 artifact 生成...手写数字是简历事故的起点,
把现存手写数字全部替换掉").

Two different kinds of pages, because they draw from two different kinds
of "real":

  - `docs/capacity-plan.md` / `docs/crossover-curve.md`: pure functions
    of already-committed config (`configs/serve/model_profiles/*.yaml`,
    `configs/bench/capacity_planning.yaml`) — real computation
    (A8's `estimate_max_concurrent_requests`/`find_concurrency_
    crossover_point`, unchanged), but every number on these pages is
    labeled a PLANNING ESTIMATE, because the inputs themselves are
    (weight_bytes/gdn_fixed_state_bytes are documented estimates, see
    those config files' own comments) — never claimed as measured.

  - `docs/metrics-summary.md`: PLAN.md A12's "六个核心数字" checklist
    (QPS/P99/MFU-MBU/瓶颈/单请求成本/crossover点), rendered from real
    `artifacts/runs/*/manifest.json` files. A run whose three pollution
    flags aren't all clean is excluded per CLAUDE.md §3.1
    (`RunManifest.is_polluted`/`assert_not_polluted`) — this script
    refuses to render a number from a polluted run, it does not just
    flag it after the fact. Zero eligible runs (the honest state of
    this sandbox — no GPU, no real bench/eval run ever executed here)
    renders an explicit PENDING marker per core number, never a
    fabricated one.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

from modelhub.bench.capacity_planning import (
    CapacityPlanningConfig,
    CrossoverResult,
    estimate_max_concurrent_requests,
    find_concurrency_crossover_point,
)
from modelhub.common.atomic_io import atomic_write_text, read_json
from modelhub.common.config import load_yaml_config
from modelhub.common.errors import Stage
from modelhub.common.run_manifest import RunManifest
from modelhub.serve.model_profile import ModelProfile, load_model_profile

_ARCTIC_PROFILE_PATH = Path("configs/serve/model_profiles/arctic_7b.yaml")
_QWEN_PROFILE_PATH = Path("configs/serve/model_profiles/qwen3_5_9b.yaml")
_CAPACITY_CONFIG_PATH = Path("configs/bench/capacity_planning.yaml")
# PLAN.md A8's own prompt-length checkpoints: "1k / 2k / 3k / 5k / 8k / 16k".
_PROMPT_TOKEN_CANDIDATES = [1000, 2000, 3000, 5000, 8000, 16000]

_PENDING = "PENDING — no clean (non-polluted) run available in this environment yet"


@dataclass(frozen=True)
class DiscoveredRuns:
    clean: list[RunManifest]
    polluted: list[RunManifest]


def discover_runs(artifacts_root: Path = Path("artifacts/runs")) -> DiscoveredRuns:
    """Scan `artifacts_root/*/manifest.json` and split into
    clean/polluted (CLAUDE.md §3.1's three flags) — a manifest that
    fails to even parse is treated as an error, not silently skipped."""
    clean: list[RunManifest] = []
    polluted: list[RunManifest] = []
    if not artifacts_root.is_dir():
        return DiscoveredRuns(clean, polluted)
    for run_dir in sorted(artifacts_root.iterdir()):
        manifest_path = run_dir / "manifest.json"
        if not manifest_path.is_file():
            continue
        manifest = RunManifest.model_validate(read_json(manifest_path))
        (polluted if manifest.is_polluted else clean).append(manifest)
    return DiscoveredRuns(clean, polluted)


def _load_profiles() -> tuple[ModelProfile, ModelProfile]:
    arctic, _ = load_model_profile(_ARCTIC_PROFILE_PATH)
    qwen, _ = load_model_profile(_QWEN_PROFILE_PATH)
    return arctic, qwen


def _load_capacity_config() -> CapacityPlanningConfig:
    config, _ = load_yaml_config(CapacityPlanningConfig, _CAPACITY_CONFIG_PATH, stage=Stage.SERVE)
    return config


def render_capacity_plan() -> str:
    arctic, qwen = _load_profiles()
    config = _load_capacity_config()
    lines = [
        "# ModelHub · Capacity Plan",
        "",
        "Generated by `scripts/render_docs.py` from "
        "`configs/serve/model_profiles/*.yaml` + `configs/bench/capacity_planning.yaml` "
        "— never hand-edited.",
        "",
        "**★ PLANNING ESTIMATE, not a measured value.** Every number below is a "
        "pure function of `weight_bytes`/`gdn_fixed_state_bytes`, both documented "
        "estimates in the source config files (see their own comments) pending "
        "confirmation from a real served model's `vLLM` startup log "
        "(`serve/vllm_log_parser.py`).",
        "",
        "| prompt tokens | Arctic-7B max concurrency | Qwen3.5-9B max concurrency |",
        "|---|---|---|",
    ]
    for prompt_tokens in _PROMPT_TOKEN_CANDIDATES:
        arctic_c = estimate_max_concurrent_requests(
            arctic,
            gpu_memory_bytes=config.gpu_memory_bytes,
            gpu_memory_utilization=config.gpu_memory_utilization,
            runtime_overhead_bytes=config.runtime_overhead_bytes,
            prompt_tokens=prompt_tokens,
            max_new_tokens=config.max_new_tokens,
        )
        qwen_c = estimate_max_concurrent_requests(
            qwen,
            gpu_memory_bytes=config.gpu_memory_bytes,
            gpu_memory_utilization=config.gpu_memory_utilization,
            runtime_overhead_bytes=config.runtime_overhead_bytes,
            prompt_tokens=prompt_tokens,
            max_new_tokens=config.max_new_tokens,
        )
        lines.append(f"| {prompt_tokens} | {arctic_c} | {qwen_c} |")
    lines.append("")
    return "\n".join(lines) + "\n"


def render_crossover_curve() -> str:
    arctic, qwen = _load_profiles()
    config = _load_capacity_config()
    result: CrossoverResult = find_concurrency_crossover_point(
        arctic,
        qwen,
        gpu_memory_bytes=config.gpu_memory_bytes,
        gpu_memory_utilization=config.gpu_memory_utilization,
        runtime_overhead_bytes=config.runtime_overhead_bytes,
        max_new_tokens=config.max_new_tokens,
        prompt_token_candidates=_PROMPT_TOKEN_CANDIDATES,
    )
    lines = [
        "# ModelHub · Arctic-7B vs Qwen3.5-9B Concurrency Crossover",
        "",
        "Generated by `scripts/render_docs.py` via "
        "`bench/capacity_planning.py::find_concurrency_crossover_point` — never hand-edited.",
        "",
        "**★ PLANNING ESTIMATE, not a measured value** — see `docs/capacity-plan.md`'s "
        "same caveat. `configs/gateway/routing.yaml`'s `schema_token_threshold` stays "
        "`threshold_source: estimate` until this crossover is confirmed by a real "
        'A8 prompt-length bench sweep (PLAN.md: "路由阈值回填 configs/gateway/").',
        "",
    ]
    if result.found:
        lines += [
            f"**Crossover found at {result.prompt_tokens} prompt tokens** — "
            f"Arctic-7B: {result.concurrency_a}, Qwen3.5-9B: {result.concurrency_b}.",
            "",
            "Scanned prompt-token checkpoints (PLAN.md's own 1k/2k/3k/5k/8k/16k):",
            "",
        ]
    else:
        lines += [
            f"**No crossover found** within the scanned range "
            f"{_PROMPT_TOKEN_CANDIDATES}. One model's estimated KV economics "
            f"dominate throughout this range.",
            "",
        ]
    lines.append("| prompt tokens | Arctic-7B | Qwen3.5-9B |")
    lines.append("|---|---|---|")
    for prompt_tokens in _PROMPT_TOKEN_CANDIDATES:
        arctic_c = estimate_max_concurrent_requests(
            arctic,
            gpu_memory_bytes=config.gpu_memory_bytes,
            gpu_memory_utilization=config.gpu_memory_utilization,
            runtime_overhead_bytes=config.runtime_overhead_bytes,
            prompt_tokens=prompt_tokens,
            max_new_tokens=config.max_new_tokens,
        )
        qwen_c = estimate_max_concurrent_requests(
            qwen,
            gpu_memory_bytes=config.gpu_memory_bytes,
            gpu_memory_utilization=config.gpu_memory_utilization,
            runtime_overhead_bytes=config.runtime_overhead_bytes,
            prompt_tokens=prompt_tokens,
            max_new_tokens=config.max_new_tokens,
        )
        lines.append(f"| {prompt_tokens} | {arctic_c} | {qwen_c} |")
    lines.append("")
    return "\n".join(lines) + "\n"


def render_metrics_summary(runs: DiscoveredRuns) -> str:
    lines = [
        "# ModelHub · Core Metrics Summary",
        "",
        "Generated by `scripts/render_docs.py` from `artifacts/runs/*/manifest.json` "
        "— never hand-edited. PLAN.md A12's six core numbers, one row each.",
        "",
        f"Clean (non-polluted) runs discovered: **{len(runs.clean)}**. "
        f"Polluted runs excluded from every number below: **{len(runs.polluted)}**.",
        "",
        "| # | metric | value | source |",
        "|---|---|---|---|",
    ]
    core_metrics = [
        "QPS",
        "P99 latency",
        "MFU/MBU",
        "bottleneck classification",
        "cost per request",
        "Arctic/Qwen3.5 concurrency crossover point",
    ]
    for i, metric in enumerate(core_metrics, start=1):
        if metric.startswith("Arctic/Qwen3.5"):
            lines.append(
                f"| {i} | {metric} | see `docs/crossover-curve.md` (estimate) | planning estimate |"
            )
        else:
            lines.append(f"| {i} | {metric} | {_PENDING} | — |")
    lines.append("")
    if runs.polluted:
        lines.append("## Excluded polluted runs")
        lines.append("")
        for m in runs.polluted:
            lines.append(f"- `{m.run_id}`: {', '.join(m.pollution_reasons())}")
        lines.append("")
    return "\n".join(lines) + "\n"


def render_all(
    *, artifacts_root: Path = Path("artifacts/runs"), docs_root: Path = Path("docs")
) -> list[Path]:
    runs = discover_runs(artifacts_root)
    pages = {
        docs_root / "capacity-plan.md": render_capacity_plan(),
        docs_root / "crossover-curve.md": render_crossover_curve(),
        docs_root / "metrics-summary.md": render_metrics_summary(runs),
    }
    written = []
    for path, content in pages.items():
        written.append(atomic_write_text(path, content))
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--artifacts-root", type=Path, default=Path("artifacts/runs"))
    parser.add_argument("--docs-root", type=Path, default=Path("docs"))
    args = parser.parse_args(argv)

    written = render_all(artifacts_root=args.artifacts_root, docs_root=args.docs_root)
    for path in written:
        print(f"render_docs: wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
