"""Thin MLflow wrapper — PLAN.md B1 item 3: "实验管理 MLflow（兼做模型
注册表后端），与 run_id 关联."

Guarded import: `mlflow` is part of the `train` extra, never installed
in this GPU-less sandbox (see docs/design-decisions.md) — real
ImportError -> SKIP, the same whitelist discipline as
`serve/kernel_status.py`. `MlflowRunHandle` tags every run with this
project's own `run_id` (not MLflow's autogenerated one) so a manifest,
the model registry, and an MLflow run can all be cross-referenced by
the same identifier.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from modelhub.common.capability import CheckStatus


@dataclass(frozen=True)
class MlflowAvailability:
    status: CheckStatus
    detail: str


def check_mlflow_available() -> MlflowAvailability:
    try:
        import mlflow  # noqa: F401
    except ImportError as e:
        return MlflowAvailability(
            CheckStatus.SKIP, f"mlflow not installed: {type(e).__name__}: {e}"
        )
    return MlflowAvailability(CheckStatus.PASS, "mlflow importable")


class MlflowRunHandle:
    def __init__(self, run_id: str) -> None:
        self.run_id = run_id

    def log_params(self, params: Mapping[str, Any]) -> None:
        import mlflow

        mlflow.log_params(dict(params))

    def log_metrics(self, metrics: Mapping[str, float], *, step: int) -> None:
        import mlflow

        mlflow.log_metrics(dict(metrics), step=step)

    def log_artifact(self, local_path: str) -> None:
        import mlflow

        mlflow.log_artifact(local_path)


def start_mlflow_run(*, experiment_name: str, run_id: str) -> MlflowRunHandle:
    """Real ImportError propagates uncaught if mlflow isn't installed —
    callers must check `check_mlflow_available()` first (CLAUDE.md §1.3:
    SKIP must never be silently treated as available)."""
    import mlflow

    mlflow.set_experiment(experiment_name)
    mlflow.start_run(run_name=run_id, tags={"modelhub_run_id": run_id})
    return MlflowRunHandle(run_id=run_id)


__all__ = [
    "MlflowAvailability",
    "MlflowRunHandle",
    "check_mlflow_available",
    "start_mlflow_run",
]
